version: '2'
services:
    1ppm-app:
        image: 1ppm
        external_links:
            - 1ppm-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/1ppm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    1ppm-postgresql:
        extends:
            file: postgresql.yml
            service: 1ppm-postgresql
